name: Lua Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  luacheck:
    name: Lint Lua Code
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Lua
      uses: leafo/gh-actions-lua@v11
      with:
        luaVersion: "5.1"
    
    - name: Setup LuaRocks
      uses: leafo/gh-actions-luarocks@v5
    
    - name: Cache LuaRocks packages
      uses: actions/cache@v4
      with:
        path: ~/.luarocks
        key: ${{ runner.os }}-luarocks-${{ hashFiles('.luacheckrc') }}
        restore-keys: |
          ${{ runner.os }}-luarocks-
    
    - name: Install luacheck
      run: luarocks install luacheck --local
    
    - name: Add LuaRocks to PATH
      run: echo "$HOME/.luarocks/bin" >> $GITHUB_PATH
    
    - name: Run luacheck
      run: |
        luacheck src/ --config .luacheckrc
        echo "✅ Lua linting completed successfully!" >> $GITHUB_STEP_SUMMARY